apiVersion : apps/v1
kind: Deployment
metadata:
  name: "website"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "website"
  template:
    metadata:
      labels:
        app: "website"
    spec:
      containers:
        - name: "website"
          image: "willclark.azurecr.io/aks"
          ports:
          - containerPort: 80
